language: node_js
node_js: [ 6 ]
cache:
    directories: [ node_modules ]
before_deploy: >
    node -e 'require("fs").writeFileSync("package.json", JSON.stringify(Object.assign(require("./package"), {version: process.env.TRAVIS_TAG})))'
deploy:
    provider: npm
    email: npm@zeroturnaround.com
    skip_cleanup: true
    api_key:
        secure: "WSSmEHQWhgS8sOkFEm8poCAofiYmDjbp4oAgi0ScrNsIpNbqLDAgwYttQjdS+h57nzeSkiSxm7ekEwAg9myOF40m9bYPAsEnOpn7OM582M5VMUMZfmZlppgy9gfGy+1ywoNcB+sdmGIJ8JJQRtfpIjlzvodc1BP3Ol/DjhBajCeLfvkdwYOruaW2yu780/k/VVZw9JKk3zZN5UVYxYbTTYUgLXoo+rjHGhoT8m86FobfxCUFKx+XaxR6JuA6UZI6XS97od3qjUq1VRwocbZOtGQNwEQ3JgYVEgqNd6SjuB8jl0D6pSq5pwbAntzJA5WRy1hQdQemjgdOwNT9fQPlbHN6qHGUxug+W+yySwwIbW8wF/wdDnOE/0bfIC6hTGBR4lH0HXUfKpyrgBt3VdoP0jBBIpLZZ0W8dnwJ14gkIDOj+oKq7FeaeGGsHoBfYNj0+7YGZsW80UD1SF+J1OCm78xIWzwcIvC16KwUoc/7KH3hp79xwPk1XplD73rtpOmTwyRBzXc/plFgc/lNZSrX7g8F9gfekVv8sibgzZ/7hkKvmrxBPXRjuHdYi7OQP94t30muJVwWk2KxJo5cBctoh4+7D3cCqd4U8pV8ZNSw0Kvf6Ii1kewaTmB0siOaDSVHwiPOzhkQw7rDgZKACJxr+jfCe/WOm+UnIL564QXw66Q="
    on:
        tags: true
