language: node_js
node_js: [ 6 ]
cache:
    directories: [ node_modules ]
before_deploy: >
    node -e 'require("fs").writeFileSync("package.json", JSON.stringify(Object.assign(require("./package"), {version: process.env.TRAVIS_TAG})))'
deploy:
    provider: npm
    email: npm@zeroturnaround.com
    skip_cleanup: true
    api_key:
        secure: KgSWMCntzjOtHBrbczWSE0BygXeVJj1Bcw/eX0lKs7lZZ57iHX0SKdFK1a7h65jNhEaMe1/V5FHyvdqh6g6ceQ7z3jNYEjl9HDNi57tU0v6vFPXpGHPbO/AoW2tANna7GwI5qcgFRs32nzFihMWiA7bhNIPLsbE1hTSmJ1YSkqI/r3NKLAYj/Kc7iqyfrJHA2SSNjFIhMZEWuM6CIQZuumzGxw/nASvBWNpkuDSLy1WCm/w/YDdl4DioGC5idAV7uuO6FGrvq7F/AuhTAWgKVZoP8o/d1rWqrBQum3Q/Gy7iTnALLTmQcZc/vk+PRpxBPyrOxbF6iWoO1eYWXT7X7W57k9MQG8YyfbpAST77UdFMK9CxqzGm28J43gYArmuk/PH9qDu8BYx+ezhqtOrxVoN3ym43Rc/LLaC5yfRJ6xuH6Cnx77s1AotptaVK09Ij64zUhClNmlGsrK1a9H08/IZKgXlXcNuf8MkkZ3a+HlVoblsnpaYnrXCR3lnhzKH0m0iTaVt6yDOwkQfQ9M7q5GoIxqKwIdLB5vh+fLvkcgJqG3gF+MizPoqBwA2PuOioBVlwSMMZORhTatxaz2VKHN3dnbPlYsJhkDG8yhsa9f6WOKDLKMiFdHZKafkLPwgvc5ZEQ5Z90LElUwReT8AcLfKzWDIc/pzmfPxhgLRF8ZI=
    on:
        tags: true
